---
title: "Lab 03 - EDA and Viz 1"
subtitle: "JSC370 (Winter 2026)"
date: "January 21, 2026"
format:
  live-html:
    toc: true
filters:
  - r-wasm/live
jupyter: python3
execute:
  enabled: false
  echo: true
  warning: false
  message: false
---


# Learning Goals

- Download [lab 3 here](https://github.com/JSC370/JSC370-2026/blob/main/labs/lab3/lab03-github.qmd)
- Read in from github and get familiar with a meteorology dataset 
- Plan out how to tackle the objective question
- Step through the EDA "checklist" presented in the class slides
- Make exploratory graphs and maps

# Deliverables

- Complete the code and summaries and upload your .qmd and rendered .html to Quercus

# Lab Description

We will work with similar meteorological data that was presented in lecture. Recall the dataset consists of weather station readings in the contiguous US. 

**The objective of the lab is to find the weather station with the lowest elevation, find out where this location is (make a map), and make a time series plot of temperature at this station.**

# Steps

### 0. Load libraries

Notes: 

- import the necessary libraries
- note setting pandas options for nicer display of the output
- in the yaml above set enabled to true when you want the code to render

```{python}
import pandas as pd
pd.set_option("display.float_format", "{:.2f}".format) 
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
import contextily as cx
from IPython.display import display
```


### 1. Read in the data

Connect to github and read in data with pandas.

```{python}
url = "https://raw.githubusercontent.com/JSC370/JSC370-2026/main/data/met_all_2025.gz"
met = pd.read_csv(url, compression="gzip")    
```

### 2. Check the memory size, dataset dimensions, and the header. How many columns, rows are there?

- fill in where there are ...

```{python}
met.memory_usage(deep=True).sum() / 1024 ** 3
```

```{python}
met.shape
```

```{python}
display(met.head)
```

Summary:
- The dataset takes memory of 2.46 Gb
- The dimension of dataset is (5381580, 30)
- The dataset has 5381580 columns and 30 rows

### 3. Look at data types of the variables in the dataset.

```{python}
met.dtypes
```

Summary:
- There are 23 columns that takes numerical type value while the others take object type

### 4. Take a closer look at the key variables (`temp` and `elev`). 

- Are there missing data in these variables? If so, make sure they are coded correctly. 
No, there is no missing values in here


```{python}
key_vars = ['temp', 'elev']

met[key_vars].isnull().sum()
```


- Are there any unusual values that look suspicious?


```{python}

minT = met.loc[met["temp"].idxmin(), "temp"]
maxT = met.loc[met["temp"].idxmax(), "temp"]

minE = met.loc[met["elev"].idxmin(), "elev"]
maxE = met.loc[met["elev"].idxmax(), "elev"]

print(minT, maxT, minE, maxE)
print("Temperature Range:", "Min:", minT, " Max:", maxT)
print("Elevation Range:", "Min:", minE, " Max:", maxE)

```

Summary:
- There is unusual value in temperature. First, the lowest temperature recorded in here is -40, which may makes sense regarding the place. However, the maximum value is 999.9, which is unusually high. It may worth to take a look to this observation. Since the code only gave 

- The highest elevation point in the dataset is 3680. While it still possible since the highest point in earth is over 8000 meters, we need to investigate more whether this data is just normal outlier or error in data input. 


### 5. Check the data against an external data source and make any other adjustments.

- Check that the range of elevations make sense. Google or ChatGPT is your friend here.
- Fix any problems that arise in your checks.

-
```{python}

met.loc[met["temp"] > 65, "temp"] = np.nan
met[['temp']].describe().round(4)

```

Summary:
- The highest point in US is around 4400 meter, which make the original value of elevation still make sense. 
- After cleaning, we can see that the maximum temperature that still in our range is 56 Celcius. THe median of the temperature is 24 Celcius, which still make sense. However, in here, the minimum temperature still -40 Celcius

```{python}
cold_temps = met[met['temp'] == -40]

# display data here extract lat and lon and check google
display(cold_temps[["temp", "lat", "lon", "month", "year"]])
```

Summary:
- For observation that has temperature of -40, based on google maps, we can see that one location is land in Mexico while the other is in Florida. Based on general knowledge, we can safely assume that place in Mexico shouldn't has temperature this low. Therefore, we may safely assume that these observations are error in data input

```{python}

# Fix up data here, remove implausible values
met = met[met["temp"] > -20].copy()
```



## 6. Answer research questions

Remember to keep the initial questions in mind. We want to pick out the weather station with minimum elevation and examine its temperature.

Some ideas for steps: 
1. subset the data for the weather station with minimum elevation
2. look at histograms of temperature
3. make a time series plot (need to create date variable)
4. make a map to see where it is


### 6a. Subset minimum elevation site

```{python}
# Subset data for the weather station with minimum elevation
minE = met.loc[met["elev"].idxmin(), "elev"]
min_elev_station = met.loc[met["elev"] == minE, :]
display(min_elev_station)
```

### 6b. Histogram of temperature at minimum elevation site

```{python}
plt.hist(min_elev_station["temp"].dropna(), bins=50)
plt.xlabel("Temperature (C)")
plt.ylabel("Count")
plt.show()
```
Summary:
- We can see that the temperature ranging from 20 into 45, which is pretty normal.

### 6c. Create date variable and time series plot

- Look at the time series of temperature at this location. For this we will need to create a date-time variable for the x-axis.

- Summarize any trends that you see in these time series plots.


```{python}
# Create a date variable for min_elev_station
min_elev_station = min_elev_station.copy()
min_elev_station['date'] = pd.to_datetime(
    min_elev_station[["year", "month", "day", "hour"]]
)

# Sort by date
min_elev_station = min_elev_station.sort_values('date')

# Create line plot of temperature by date

plt.plot(min_elev_station["date"], min_elev_station["temp"])
plt.xlabel("Date")
plt.ylabel("Temperature (C)")
plt.grid(True, alpha=0.3)
plt.xticks(rotation=45)
plt.show()
```

Summarize time series plot:
- We can see that the temperature is osicillating between 20 into 40. We can also see that the lowest temperature is roughly stable in 20 Celcius. However, we can also see that overtime, the highest point of osicillation is get higher, until at some points, it reached over 45 Celcius. F

### 6d. Where is the lowest weather station?

```{python}
station_location = min_elev_station[["lat", "lon", "elev"]].drop_duplicates()

lat = station_location['lat'].iloc[0]
lon = station_location['lon'].iloc[0]
elev = station_location['elev'].iloc[0]

# make elev into GeoDataFrame for mapping
gdf = gpd.GeoDataFrame(
    {'elevation': [elev]},
    geometry=gpd.points_from_xy([lon], [lat]),
    crs='EPSG:4326'
)

# Convert to Web Mercator for basemap
gdf = gdf.to_crs('EPSG:3857')

# map
fig, ax = plt.subplots(figsize=(10, 8))
gdf.plot(ax=ax, color='red', markersize=300, marker='*', edgecolor='black', linewidth=2, zorder=5)
cx.add_basemap(ax, source=cx.providers.OpenStreetMap.Mapnik)
ax.set_xlabel('Longitude')
ax.set_ylabel('Latitude')
ax.set_title(f'Lowest Elevation Station (Elevation: {elev} m)')
plt.show()
```

Summarize where the lowest elevation station is located.
- The location is a dessert in California.